name: Value Rotation Scanner

on:
  workflow_dispatch:

  schedule:
    - cron: "55 3 * * 1-5"

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy ta requests

      - name: Run Scanner
        run: python value_rotation_scanner.py
